schema_version = "1.0.0"

id = "right_mouse_navigation"
version = "2.5.2"
name = "Right Mouse Navigation"
tagline = "Game Engine Movement and Menus"
maintainer = "Spectral Vectors and Contributors"
type = "add-on"

website = "https://github.com/SpectralVectors/RightMouseNavigation"

tags = ["3D View", "Node", "User Interface"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]
